export default {
  containerPaddingV: 24,
  containerPaddingH: 24,
  containerMarginT: 40,
  titleMarginT: 50,
  fontTitle: 24,
  fontText: 14,
  cardPadding: 24,
  cardMargin: 16,
  cardBorderRadius: 8,
  cardTextMargin: 8,
  cardShadowWidth: 0,
  cardShadowHeight: 2,
  cardShadowRadius: 6,
  cardShadowOpacity: 0.32,
  cardElevation: 10,
  buttonPaddingPrimary: 10,
  buttonPaddingSecondary: 20,
  buttonBorderRadius: 8,
  fontButton: 18,
  inputPadding: 10,
  inputMargin: 10,
  inputHeight: 55,
  inputWidth: '80%',
  inputBorderWidth: 1,
  inputBorderRadius: 5,
}